apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glas-ljudstva
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - staging.yaml
images:
- name: glas-ljudstva
  newName: rg.fr-par.scw.cloud/djnd/glas-ljudstva
  newTag: 'd5f6d38dded0f9c189b844d94e35ea497327de1f'
- name: glas-ljudstva-staging
  newName: rg.fr-par.scw.cloud/djnd/glas-ljudstva-staging
  newTag: 'd5f6d38dded0f9c189b844d94e35ea497327de1f'
