apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glas-ljudstva
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - staging.yaml
images:
- name: glas-ljudstva
  newName: rg.fr-par.scw.cloud/djnd/glas-ljudstva
  newTag: '70375e0c4ebd6ca49b3b9dc14c905b4d501d1ffe'
- name: glas-ljudstva-staging
  newName: rg.fr-par.scw.cloud/djnd/glas-ljudstva-staging
  newTag: '70375e0c4ebd6ca49b3b9dc14c905b4d501d1ffe'
