apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glas-ljudstva
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - staging.yaml
images:
- name: glas-ljudstva
  newName: rg.fr-par.scw.cloud/djnd/glas-ljudstva
  newTag: '1a4e0acb87f6272686fc0843fcb51e321686b573'
- name: glas-ljudstva-staging
  newName: rg.fr-par.scw.cloud/djnd/glas-ljudstva-staging
  newTag: '1a4e0acb87f6272686fc0843fcb51e321686b573'
