apiVersion: apps/v1
kind: Deployment
metadata:
  name: glas-ljudstva-staging-deployment
  labels:
    app: glas-ljudstva-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glas-ljudstva-staging
  template:
    metadata:
      labels:
        app: glas-ljudstva-staging
    spec:
      volumes:
        - name: glas-ljudstva-staging-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: glas-ljudstva-staging
          volumeMounts:
            - name: glas-ljudstva-staging-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: glasljudstva.k8s_settings
          envFrom:
            - secretRef:
                name: glas-ljudstva-staging-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 500m
        - name: migrate
          image: glas-ljudstva-staging
          volumeMounts:
            - name: glas-ljudstva-staging-storage
              mountPath: /storage
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: glasljudstva.k8s_settings
          envFrom:
            - secretRef:
                name: glas-ljudstva-staging-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 500m
      containers:
        - name: glas-ljudstva-staging
          image: glas-ljudstva-staging
          volumeMounts:
            - name: glas-ljudstva-staging-storage
              mountPath: /storage
          command:
            - gunicorn
            - glasljudstva.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "120"
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: glasljudstva.k8s_settings
          envFrom:
            - secretRef:
                name: glas-ljudstva-staging-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 500m
        - name: glas-ljudstva-staging-nginx
          image: nginx:alpine
          volumeMounts:
            - name: glas-ljudstva-staging-storage
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: glas-ljudstva-staging
spec:
  selector:
    app: glas-ljudstva-staging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: glas-ljudstva-staging-nginx
spec:
  selector:
    app: glas-ljudstva-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glas-ljudstva-staging
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging.glas-ljudstva.si
      secretName: glas-ljudstva-staging-tls
  rules:
    - host: staging.glas-ljudstva.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glas-ljudstva-staging
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glas-ljudstva-staging-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.staging.glas-ljudstva.si
      secretName: glas-ljudstva-staging-nginx-tls
  rules:
    - host: files.staging.glas-ljudstva.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glas-ljudstva-staging-nginx
                port:
                  number: 80
