# Generated by Django 4.1.3 on 2024-02-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizations', models.TextField(blank=True, verbose_name='Organizacije')),
                ('organizations_count', models.PositiveIntegerField(default=0, verbose_name='Število organizacij')),
            ],
            options={
                'verbose_name': 'Domača stran',
                'verbose_name_plural': 'Domača stran',
            },
        ),
        migrations.CreateModel(
            name='SideBarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('gap', models.BooleanField(default=False, verbose_name='Presledek')),
                ('icon', models.CharField(choices=[('eye', 'Oko'), ('handshake', 'Roka')], default='handshake', max_length=100, verbose_name='Ikona')),
                ('title', models.CharField(max_length=100, verbose_name='Naslov')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Opis')),
                ('url', models.CharField(max_length=512, verbose_name='Povezava')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.landingpageconfig', verbose_name='Domača stran')),
            ],
            options={
                'verbose_name': 'Povezava v stranski vrstici',
                'verbose_name_plural': 'Povezave v stranski vrstici',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
