# Generated by Django 4.1.3 on 2024-02-09 18:50

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Naslov")),
                ("publish_time", models.DateTimeField(verbose_name="Čas objave")),
                (
                    "intro",
                    martor.models.MartorField(
                        blank=True, null=True, verbose_name="Uvod"
                    ),
                ),
                (
                    "content",
                    martor.models.MartorField(
                        blank=True, null=True, verbose_name="Vsebina"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Objavljeno"),
                ),
            ],
            options={
                "verbose_name": "Novica",
                "verbose_name_plural": "Novice",
            },
        ),
    ]
