# Generated by Django 4.1.3 on 2024-02-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryNavBarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=100, verbose_name='Naslov')),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Povezava')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.landingpageconfig', verbose_name='Domača stran')),
            ],
            options={
                'verbose_name': 'Povezava v sekundarni navigaciji',
                'verbose_name_plural': 'Povezave v sekundarni navigaciji',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryNavBarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=100, verbose_name='Naslov')),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Povezava')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.landingpageconfig', verbose_name='Domača stran')),
            ],
            options={
                'verbose_name': 'Povezava v glavni navigaciji',
                'verbose_name_plural': 'Povezave v glavni navigaciji',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
