# Generated by Django 4.1.3 on 2024-02-15 17:36

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_secondarynavbarlink_primarynavbarlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Naslov")),
                (
                    "intro",
                    martor.models.MartorField(
                        blank=True, null=True, verbose_name="Uvod"
                    ),
                ),
                (
                    "content",
                    martor.models.MartorField(
                        blank=True, null=True, verbose_name="Vsebina"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Objavljeno"),
                ),
                (
                    "promoted",
                    models.BooleanField(
                        default=False, verbose_name="Izpostavljeno na domači strani"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampanja",
                "verbose_name_plural": "Kampanje",
            },
        ),
    ]
