# Generated by Django 4.1.3 on 2024-02-15 18:02

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("home", "0006_campaignitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignitem",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_image",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Slika",
            ),
        ),
    ]
