# Generated by Django 4.1.3 on 2024-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_campaignitem_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignitem",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Kampanja",
                "verbose_name_plural": "Kampanje",
            },
        ),
        migrations.AddField(
            model_name="campaignitem",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="ordering"),
        ),
    ]
