# Generated by Django 4.1.3 on 2026-05-21 14:45

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_sidebarlink_gap_sidebarlink_red"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationPageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Naslov")),
                (
                    "content",
                    martor.models.MartorField(
                        blank=True, null=True, verbose_name="Vsebina"
                    ),
                ),
                (
                    "donation_once_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Naslov za enkratno donacijo",
                    ),
                ),
                (
                    "donation_once_description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Opis za enkratno donacijo",
                    ),
                ),
                (
                    "donation_once_button_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Besedilo na gumbu za enkratno donacijo",
                    ),
                ),
                ("donation_once_url", models.URLField()),
                (
                    "donation_recurring_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Naslov za mesečno donacijo",
                    ),
                ),
                (
                    "donation_recurring_description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Opis za mesečno donacijo",
                    ),
                ),
                (
                    "donation_recurring_button_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Besedilo na gumbu za mesečno donacijo",
                    ),
                ),
                ("donation_recurring_url", models.URLField()),
            ],
            options={
                "verbose_name": "Donacijska stran",
                "verbose_name_plural": "Donacijske strani",
            },
        ),
    ]
