# Generated by Django 4.1.3 on 2026-06-03 14:36

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_donationpageconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sidebarlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("box-title", "Naslov polja"),
                    ("eye", "Oko"),
                    ("handshake", "Dokument"),
                    ("support", "Podpora"),
                    ("email", "E-pošta"),
                ],
                default="handshake",
                max_length=100,
                verbose_name="Ikona",
            ),
        ),
        migrations.CreateModel(
            name="FooterBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(default=0, verbose_name="ordering"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("box-title", "Naslov polja"),
                            ("eye", "Oko"),
                            ("handshake", "Dokument"),
                            ("support", "Podpora"),
                            ("email", "E-pošta"),
                        ],
                        default="handshake",
                        max_length=100,
                        verbose_name="Ikona",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Naslov")),
                (
                    "content",
                    martor.models.MartorField(
                        blank=True, null=True, verbose_name="Vsebina"
                    ),
                ),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.landingpageconfig",
                        verbose_name="Domača stran",
                    ),
                ),
            ],
            options={
                "verbose_name": "Škatla v nogi strani",
                "verbose_name_plural": "Škatle v nogi strani",
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
    ]
