# Generated by Django 4.1.3 on 2026-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_sidebarlink_icon_footerbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Ime strani v povezavi (npr. glas-ljudstva.si/objava/kljuc-za-povezavo/, pusti prazno za samodejno generiranje ključa)",
                max_length=200,
                verbose_name="Ključ za povezavo",
            ),
        ),
    ]
