# Generated by Django 4.1.3 on 2026-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_contentpage_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageconfig",
            name="privacy_policy_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Povezava do politike zasebnosti",
            ),
        ),
    ]
