# Generated by Django 4.1.3 on 2026-06-10 09:59

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_landingpageconfig_privacy_policy_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageconfig",
            name="footer_text",
            field=martor.models.MartorField(
                blank=True, null=True, verbose_name="Besedilo v nogi strani"
            ),
        ),
    ]
