from django.urls import include, path

from zahteve.views import (
    MissingPartiesList,
    MunicipalitiesList,
    PartyDemand,
    QuestionsByMunicipalities,
    Registracija,
    RestorePasswordView,
    Volitvomat,
    after_registration,
    amandma,
    delovna_skupina,
    demand,
    demands_party,
    faq,
    landing,
    monitoring,
    monitoring_report,
    omnia,
    open_party_summary,
    party,
    party_finish,
    party_instructions,
    party_save,
    party_summary,
    verify_email,
)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("", include("home.urls")),
    # path('', landing),
    path("amandma-ZZVZZ/", amandma),
    path("omnia/", omnia),
    path("<int:delovna_skupina_id>/", delovna_skupina),
    path("zahteve/<int:demand_id>/", demand),
    path("zahteve/stranka/<int:party_id>/", demands_party),
    path("zahteve/", landing),
    path("pogosta-vprasanja/", faq),
    path("", include("django.contrib.auth.urls")),
    path("comments/", include("django_comments.urls")),
    path("registracija/", Registracija.as_view()),
    path("potrdi-naslov/<str:token>/", verify_email),
    path("ponastavi-geslo/<str:parameter>/", RestorePasswordView.as_view()),
    path("ponastavi-geslo/", RestorePasswordView.as_view()),
    path("hvala/", after_registration),
    path("monitoring/", monitoring),
    path("monitoring/<slug:election_slug>/", monitoring),
    path("monitoring-zaveze/<int:monitoring_report_id>/", monitoring_report),
    path("<slug:election_slug>/", landing),
    path("<slug:election_slug>/zahteve/", landing),
    path("<slug:election_slug>/zahteve/<int:demand_id>/", demand),
    path("<slug:election_slug>/zahteve/stranka/<int:party_id>/", demands_party),
    path("<slug:election_slug>/skupina/<int:delovna_skupina_id>/", delovna_skupina),
    # URLS for candidates, twice. this is just cosmetics
    # first for parties
    path("<slug:election_slug>/stranke/", party),
    path("<slug:election_slug>/stranke/<int:category_id>/", PartyDemand.as_view()),
    path("<slug:election_slug>/stranke/navodila/", party_instructions),
    path("<slug:election_slug>/stranke/oddaja/", party_finish),
    path("<slug:election_slug>/stranke/oddaj/", party_save),
    path("<slug:election_slug>/stranke/povzetek/", party_summary),
    path("<slug:election_slug>/stranke/povzetek/<int:party_id>/", open_party_summary),
    # then for individual candidates
    path("<slug:election_slug>/kandidati_ke/", party),
    path("<slug:election_slug>/kandidati_ke/<int:category_id>/", PartyDemand.as_view()),
    path("<slug:election_slug>/kandidati_ke/navodila/", party_instructions),
    path("<slug:election_slug>/kandidati_ke/oddaja/", party_finish),
    path("<slug:election_slug>/kandidati_ke/oddaj/", party_save),
    path("<slug:election_slug>/kandidati_ke/povzetek/", party_summary),
    path(
        "<int:election_id>/api/volitvomat/missing-parties/<slug:municipality_slug>",
        MissingPartiesList.as_view(),
    ),
    path(
        "<int:election_id>/api/volitvomat/<slug:municipality_id>", Volitvomat.as_view()
    ),
    path("<int:election_id>/api/volitvomat/", Volitvomat.as_view()),
    path("api/volitvomat/municipalities", MunicipalitiesList.as_view()),
    path("api/volitvomat/", Volitvomat.as_view()),
    path("api/municipalities/", QuestionsByMunicipalities.as_view()),
]
