# Generated by Django 3.2.9 on 2021-11-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid from", null=True
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid from", null=True
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, default=None, help_text="row valid to", null=True
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "workgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zahteve.workgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
