# Generated by Django 3.2.9 on 2021-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='voices',
            field=models.IntegerField(default=0),
        ),
    ]
