# Generated by Django 3.2.9 on 2021-11-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0002_demand_voices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="voices",
        ),
    ]
