# Generated by Django 3.2.9 on 2021-11-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0002_emailverification'),
        ('zahteve', '0003_remove_demand_voices'),
    ]

    operations = [
    ]
