# Generated by Django 3.2.9 on 2021-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0004_merge_20211112_1114"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="newsletter_permission",
            field=models.BooleanField(default=False),
        ),
    ]
