# Generated by Django 3.2.9 on 2021-11-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0005_emailverification_newsletter_permission"),
        ("zahteve", "0006_auto_20211112_1434"),
    ]

    operations = []
