# Generated by Django 3.2.9 on 2021-11-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('zahteve', '0008_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('permission', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
