# Generated by Django 4.0.1 on 2022-01-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0011_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_with_demand', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahteve.demand')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahteve.party')),
            ],
        ),
    ]
