# Generated by Django 4.0.1 on 2022-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0012_demandanswer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='demandanswer',
            constraint=models.UniqueConstraint(fields=('party', 'demand'), name='unique_party_demand'),
        ),
    ]
