# Generated by Django 4.0.1 on 2022-01-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0013_demandanswer_unique_party_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='finished_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
