# Generated by Django 4.0.1 on 2022-01-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0016_party_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='priority_demand',
            field=models.BooleanField(default=False),
        ),
    ]
