# Generated by Django 4.0.1 on 2022-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0017_demand_priority_demand"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="image",
            field=models.ImageField(null=True, upload_to="party-images"),
        ),
        migrations.AddField(
            model_name="party",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
