# Generated by Django 4.0.3 on 2022-03-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0019_alter_party_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('hometown', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=120)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
