# Generated by Django 4.0.3 on 2022-08-11 17:24

from django.db import migrations, models
import django.db.models.deletion

def create_election(apps, schema_editor):
    # Get models
    Election = apps.get_model('zahteve.election')

    initial_election = Election.objects.create(
        name="Državnozborske volitve 2022",
        slug="drzavnozborske-volitve-2022",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0021_election'),
    ]

    operations = [
        migrations.RunPython(create_election),
        migrations.AddField(
            model_name='demand',
            name='election',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='zahteve.election'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='election',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='zahteve.election'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workgroup',
            name='election',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='zahteve.election'),
            preserve_default=False,
        ),
    ]
