# Generated by Django 4.1 on 2022-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0022_demand_election_party_election_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
