# Generated by Django 4.1.2 on 2022-10-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0024_municipality_demand_municipality_party_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zahteve.municipality'),
        ),
    ]
