# Generated by Django 4.1.2 on 2022-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0028_alter_demand_options_alter_demandanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
