# Generated by Django 4.1.3 on 2022-11-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahteve', '0029_municipality_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='mautic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
