# Generated by Django 4.1.3 on 2023-01-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0033_demandstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringreport",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zahteve.demandstate",
                verbose_name="Napredek pri uresničevanju zaveze:",
            ),
        ),
    ]
