# Generated by Django 4.1.3 on 2023-02-06 12:31

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0035_alter_workgroup_options_workgroup_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringreport",
            name="notes",
            field=martor.models.MartorField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Opombe (max 1000 znakov)",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringreport",
            name="summary",
            field=martor.models.MartorField(
                blank=True,
                max_length=5000,
                null=True,
                verbose_name="Kratek povzetek ugotovitev o  uresničevanju zaveze (max 5000 znakov)",
            ),
        ),
    ]
