# Generated by Django 4.1.3 on 2023-02-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0038_alter_monitoringreport_cooperative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringreport",
            name="cooperative",
            field=models.TextField(
                blank=True,
                choices=[("yes", "Da"), ("no", "Ne")],
                verbose_name="Državni organ(i) so iniciativi Glas ljudstva poslali pojasnila/odgovor o uresničevanju zaveze",
            ),
        ),
    ]
