# Generated by Django 4.1.3 on 2024-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0039_alter_monitoringreport_cooperative"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringreport",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Objavi?"),
            preserve_default=False,
        ),
    ]
