# Generated by Django 4.1.3 on 2026-01-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0041_alter_monitoringreport_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zahteve.municipality",
                verbose_name="Občina",
            ),
        ),
    ]
