# Generated by Django 4.1.3 on 2026-01-26 10:29

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0042_alter_party_municipality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="description",
            field=martor.models.MartorField(
                blank=True, max_length=10000, null=True, verbose_name="Dodaten opis"
            ),
        ),
    ]
