# Generated by Django 4.1.3 on 2026-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0043_alter_demand_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="list_title",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Naslov (za prikaz na seznamu, če je prazno se prikazuje 'Vprašanje')",
            ),
        ),
    ]
