# Generated by Django 4.1.3 on 2026-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0044_demand_list_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="our_answers",
            field=models.BooleanField(
                default=False,
                verbose_name="To so naši odgovori (stranka ni oddala vprašalnika)",
            ),
        ),
    ]
