# Generated by Django 4.1.3 on 2026-02-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0045_party_our_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolitvomatDisplayedDemands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_ids",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="ID-ji vprašanj, ki se prikazujejo v volitvomatih (če je prazno, se prikazujejo vsa)",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zahteve.election",
                        verbose_name="Volitve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prikazana vprašanja na volitvomatu",
                "verbose_name_plural": "Prikazana vprašanja na volitvomatu",
            },
        ),
    ]
