# Generated by Django 4.1.3 on 2026-03-05 10:03

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zahteve", "0046_volitvomatdisplayeddemands"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="simple_description",
            field=martor.models.MartorField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Preprost opis (za prikaz na volitvomatu)",
            ),
        ),
        migrations.AddField(
            model_name="demand",
            name="simple_title",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Preprost naslov (za prikaz na volitvomatu)",
            ),
        ),
    ]
